CREATE OR REPLACE VIEW CHURN_RISK_COMPLAINTS AS
SELECT
    COMPLAINT_ID,
    DATE_RECEIVED,
    PRODUCT,
    SUB_PRODUCT,
    ISSUE,
    COMPLAINT_NARRATIVE,
    COMPANY,
    STATE,
    COMPANY_RESPONSE,
    TIMELY_RESPONSE,
    CASE
        WHEN COMPANY_RESPONSE ILIKE '%closed without relief%'
          OR COMPANY_RESPONSE ILIKE '%untimely response%'
          OR TIMELY_RESPONSE = 'No'
          OR COMPANY_RESPONSE ILIKE '%closed with explanation%' THEN 'At Risk'
        ELSE 'Retained'
    END AS CHURN_LABEL
FROM RAW_COMPLAINTS
WHERE COMPLAINT_NARRATIVE IS NOT NULL;
